import fs from "fs";
import path from "path";
import {
    Transform
} from "stream";

const HTMLTemplatePath = "util/html/Template.js";
const HTMLGlobalStylePath = "util/html/GlobalStyle.js";

const LNBR_SEQ = /(?:\r\n|\n|\r)/g;
const IMPORT_SCRIPT = /^\s*import(?:\s+([a-zA-Z0-9_$]+)\s+from)?\s+"([^"]+)"\s*;?$/;
const IMPORT_ASSERT = /^\s*import\s+([a-zA-Z0-9_$]+)\s+from\s+"([^"]+)"\s+assert\s+\{\s*type:\s*"([^"]+)"\s*\}\s*;?$/;

function normalizePath(path) {
    return path.replace(/\\/g, "/");
}

function augmentFile(emcJSPrefix, sourcePath, fileContent) {
    const sourceDir = path.dirname(sourcePath);
    // lists
    const importedHTML = [];
    const importedCSS = [];
    const importedJSON = [];
    // analyzer
    const script = fileContent.split(LNBR_SEQ).map((string) => {
        // check asserted import
        const isAssertImport = IMPORT_ASSERT.exec(string);
        if (isAssertImport != null) {
            const name = isAssertImport[1];
            const filePath = isAssertImport[2];
            const fileType = isAssertImport[3];
            switch (fileType) {
                case "html": {
                    importedHTML.push({
                        name, filePath
                    });
                    return null;
                }
                case "css": {
                    importedCSS.push({
                        name, filePath
                    });
                    return null;
                }
                case "json": {
                    importedJSON.push({
                        name, filePath
                    });
                    return null;
                }
            }
            return string;
        }
        // check folder import
        const isScriptImport = IMPORT_SCRIPT.exec(string);
        if (isScriptImport != null) {
            const name = isScriptImport[1];
            const filePath = isScriptImport[2];
            if (!filePath.endsWith(".js")) {
                if (name == null) {
                    return `import "${filePath}/index.js";`;
                }
                return `import ${name} from "${filePath}/index.js";`;
            }
        }
        return string;
    }).filter((e) => e != null).join("\n");

    let result = "";
    if (importedCSS.length || importedHTML.length || importedJSON.length) {
        result += "/* ===================== AUTOGENERATED SOURCE IMPORT ===================== */\n\n";

        // HTML
        if (importedHTML.length) {
            // import Template module
            const modulePath = normalizePath(`${emcJSPrefix}/${HTMLTemplatePath}`);
            result += `import Template from "${modulePath}";\n`;
            // include files
            for (const {name, filePath} of importedHTML) {
                const resolvedPath = path.resolve(sourceDir, filePath);
                // if the file exists
                if (fs.existsSync(resolvedPath)) {
                    const fileContent = fs.readFileSync(resolvedPath).toString();
                    result += `const ${name} = new Template(\`\n${fileContent}\n\`);\n`;
                }
            }
            result += "\n";
        }

        // CSS
        if (importedCSS.length) {
            // import GlobalStyle module
            const modulePath = normalizePath(`${emcJSPrefix}/${HTMLGlobalStylePath}`);
            result += `import GlobalStyle from "${modulePath}";\n`;
            // include files
            for (const {name, filePath} of importedCSS) {
                const resolvedPath = path.resolve(sourceDir, filePath);
                // if the file exists
                if (fs.existsSync(resolvedPath)) {
                    const fileContent = fs.readFileSync(resolvedPath).toString();
                    result += `const ${name} = new GlobalStyle(\`\n${fileContent}\n\`);\n`;
                }
            }
            result += "\n";
        }

        // JSON
        if (importedJSON.length) {
            // include files
            for (const {name, filePath} of importedJSON) {
                const resolvedPath = path.resolve(sourceDir, filePath);
                // if the file exists
                if (fs.existsSync(resolvedPath)) {
                    const fileContent = fs.readFileSync(resolvedPath).toString();
                    result += `const ${name} = ${fileContent};\n`;
                }
            }
            result += "\n";
        }

        result += "/* ======================================================================= */\n\n";
    }
    return result + script;
}

export default function sourceImport(emcJSPrefix = "/emcJS") {
    // augment
    const transformStream = new Transform({objectMode: true});
    transformStream._transform = function(file, encoding, callback) {
        const contents = augmentFile(emcJSPrefix, file.path, String(file.contents));
        if (file.isBuffer() === true) {
            file.contents = Buffer.from(contents);
        } else {
            file.contents = contents;
        }
        callback(null, file);
    };
    return transformStream;
}
